name: "ZAP docker CI workflow"


on:
  push:
    branches: [ main ]
  schedule:
      - cron:  '0 0 1 * *' ##execution of a task in the first minute of the month 


jobs:

# https://www.zaproxy.org/docs/docker/about/
 ubuntu-latest-zap-full-basic-job:
    name: "ZAP docker"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status  
    - name: "ZAP CLI"
      run: | 
          docker run -i owasp/zap2docker-stable zap-cli quick-scan --self-contained \
            --start-options '-config api.disablekey=true' http://testphp.vulnweb.com  





